# Project: Project15
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = Airline.o Exception.o Flight.o Ticket.o Main.o Passenger.o
LINKOBJ  = Airline.o Exception.o Flight.o Ticket.o Main.o Passenger.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project15.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

Airline.o: Airline.cpp
	$(CPP) -c Airline.cpp -o Airline.o $(CXXFLAGS)

Exception.o: Exception.cpp
	$(CPP) -c Exception.cpp -o Exception.o $(CXXFLAGS)

Flight.o: Flight.cpp
	$(CPP) -c Flight.cpp -o Flight.o $(CXXFLAGS)

Ticket.o: Ticket.cpp
	$(CPP) -c Ticket.cpp -o Ticket.o $(CXXFLAGS)

Main.o: Main.cpp
	$(CPP) -c Main.cpp -o Main.o $(CXXFLAGS)

Passenger.o: Passenger.cpp
	$(CPP) -c Passenger.cpp -o Passenger.o $(CXXFLAGS)
